[build]
  base = "./"
  publish = ".vitepress/dist"
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# pluginz
# https://github.com/netlify/netlify-plugin-lighthouse#readme
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

[[redirects]]
  from = "https://tanaab-www.netlify.app/*"
  to = "https://www.tanaab.dev/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://tanaab.systems/*"
  to = "https://www.tanaab.dev/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.tanaab.systems/*"
  to = "https://www.tanaab.dev/:splat"
  status = 301
  force = true
